---
- name: install packages and use handler for notifications
  hosts: controller
  tasks: 
  - name: " Install epel release "
    yum: 
      name: epel-release
      state: latest
  - name: " Install Nginx "
    yum:
      name: nginx
      state: latest
    notify: 
      - restart and enable
  handlers: 
  - name: restart and enable
    service: 
       name: nginx
       state: resstarted
   
